---
- name: Join Control Plane Nodes to Cluster
  vars:
    join_control_plane: lookup('file','/tmp/kubeadm-join-control-plane.txt')
  shell: 'export KUBELET_EXTRA_ARGS="--cloud-provider=external" && {{ join_control_plane }}'
