---
- name: Adding CRI-O Signing Key
  apt_key:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O Repository
  copy:
    dest: /etc/apt/sources.list.d/cri-o.list
    content: |
      deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /
    mode: "0644"
