---
- name: Join Workers Nodes to Cluster
  vars:
    join_worker: lookup('file','/tmp/kubeadm-join-worker.txt')
  shell: 'export KUBELET_EXTRA_ARGS="--cloud-provider=external" && {{ join_worker }}''
